# Generated by Django 4.0.1 on 2022-01-27 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_desc', models.CharField(max_length=200)),
                ('property_city', models.CharField(max_length=50)),
                ('property_address', models.CharField(max_length=200)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property_owner', models.CharField(max_length=60)),
                ('property_contact', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
