# Generated by Django 4.0.1 on 2022-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_desc', models.CharField(max_length=200)),
                ('property_city', models.CharField(max_length=50)),
                ('property_address', models.CharField(max_length=200)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property_owner', models.CharField(max_length=60)),
                ('property_contact', models.CharField(max_length=10)),
            ],
        ),
    ]
